apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchat-deployment
  labels:
    app: techchat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchat
  template:
    metadata:
      labels:
        app: techchat
    spec:
      containers:
      - name: techchat-container
        image: docker.io/lasitha667/travel_guide_devops-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/tour"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
